spring:
  mvc:
    format:
      date: iso
  liquibase:
    enabled: true
  datasource:
    #    url: jdbc:mysql://ovz1.j71491578.pr46m.vps.myjino.ru:49516/comand_DB?useUnicode=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    #    username: xuser
    #    password: gidadi69
    url: jdbc:mysql://localhost:3306/network
    username: root
    password: 1azX2sxC3dcV12/*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
logging:
  level:
    root: INFO
#  file.name: logging.log